# Generated by Django 4.2.1 on 2023-07-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_created_at_user_is_verified_user_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_verified",
            new_name="is_email_verified",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
