# Generated by Django 4.2.1 on 2023-07-27 09:09

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_emailconfirmationtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Random",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
            managers=[
                ("random", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("RECRUITER", "Recruiter"),
                    ("CANDIDATE", "Candidate"),
                    ("RANDOM", "Random"),
                ],
                max_length=50,
            ),
        ),
    ]
