# Generated by Django 4.2.1 on 2023-05-30 10:08

import afritechjobsapi.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_details', models.TextField()),
                ('banner_image', models.ImageField(upload_to='event')),
                ('event_host', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField()),
                ('registration_fees', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_attending', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('is_email_confirmed', models.BooleanField(default=False)),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name='WorkResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='blog/%Y/%m/%d')),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('meta_description', models.CharField(blank=True, max_length=150, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('post_status', models.BooleanField(default=False)),
                (
                    'author',
                    models.ForeignKey(
                        default=afritechjobsapi.models.WorkResources.deleted_author_replacement_default,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to='afritechjobsapi.profile',
                    ),
                ),
                ('category', models.ManyToManyField(blank=True, null=True, to='afritechjobsapi.category')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='blog/%Y/%m/%d')),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('meta_description', models.CharField(blank=True, max_length=150, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('post_status', models.BooleanField(default=False)),
                (
                    'author',
                    models.ForeignKey(
                        default=afritechjobsapi.models.Blog.deleted_author_replacement_default,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to='afritechjobsapi.profile',
                    ),
                ),
                ('category', models.ManyToManyField(blank=True, null=True, to='afritechjobsapi.category')),
            ],
        ),
    ]
