# Generated by Django 4.2.1 on 2023-06-01 06:15

import afritechjobsapi.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('afritechjobsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(
                default=afritechjobsapi.models.Event.deleted_author_replacement_default,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to='afritechjobsapi.profile',
            ),
        ),
    ]
