# Generated by Django 4.2.1 on 2023-06-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afritechjobsapi', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
