# Generated by Django 4.2.1 on 2023-06-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afritechjobsapi', '0007_remove_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='banner_image',
        ),
    ]
