# Generated by Django 4.2.1 on 2023-06-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afritechjobsapi', '0008_remove_event_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workresources',
            name='image',
        ),
        migrations.RemoveField(
            model_name='workresources',
            name='slug',
        ),
    ]
