# Generated by Django 4.2.1 on 2023-06-06 14:43

import afritechjobsapi.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('afritechjobsapi', '0009_remove_workresources_image_remove_workresources_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'job_level_choices',
                    models.CharField(
                        choices=[
                            ('ST', 'Student'),
                            ('IN', 'Intern'),
                            ('EL', 'Entrylevel'),
                            ('ML', 'Midlevel'),
                            ('SL', 'Seniorlevel'),
                            ('CF', 'Cofounder'),
                            ('DC', 'Director'),
                            ('MG', 'Manager'),
                            ('CEO', 'ChiefExecutiveOfficer'),
                            ('CTO', 'ChiefTechnologyOfficer'),
                            ('CMO', 'ChiefMarketingOfficer'),
                            ('CFO', 'Chief Financial Officer'),
                            ('COO', 'Chief Operating Officer'),
                        ],
                        default='EL',
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('DJ', 'Django'), ('RT', 'React')], default='DJ', max_length=20)),
                ('category', models.ManyToManyField(to='afritechjobsapi.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afritechjobsapi.profile')),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'job_type_choices',
                    models.CharField(
                        choices=[
                            ('CT', 'Contract'),
                            ('FT', 'FullTime'),
                            ('FL', 'Freelance'),
                            ('IP', 'Internship'),
                            ('PT', 'Parttime'),
                        ],
                        default='FT',
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='PostAJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_salary_range', models.IntegerField(blank=True)),
                ('job_description', models.TextField()),
                ('job_application_link', models.URLField()),
                ('company_name', models.CharField(max_length=200)),
                ('company_hq', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(upload_to='')),
                ('companys_website', models.URLField()),
                ('company_contact_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('company_description', models.TextField()),
                (
                    'job_category',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afritechjobsapi.category'),
                ),
                (
                    'job_level',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afritechjobsapi.joblevel'),
                ),
                (
                    'job_location',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afritechjobsapi.joblocation'),
                ),
                (
                    'job_skills',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='afritechjobsapi.jobskills',
                    ),
                ),
                (
                    'job_type',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afritechjobsapi.jobtype'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='HiringGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('meta_description', models.CharField(blank=True, max_length=150, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('post_status', models.BooleanField(default=False)),
                (
                    'author',
                    models.ForeignKey(
                        default=afritechjobsapi.models.HiringGuide.deleted_author_replacement_default,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to='afritechjobsapi.profile',
                    ),
                ),
                ('category', models.ManyToManyField(blank=True, null=True, to='afritechjobsapi.category')),
            ],
        ),
    ]
