# Generated by Django 4.2.1 on 2023-06-02 11:33

import afritechjobsapi.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afritechjobsapi', '0009_remove_workresources_image_remove_workresources_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('meta_description', models.CharField(blank=True, max_length=150, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('post_status', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=afritechjobsapi.models.HiringGuide.deleted_author_replacement_default, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='afritechjobsapi.profile')),
                ('category', models.ManyToManyField(blank=True, null=True, to='afritechjobsapi.category')),
            ],
        ),
    ]
