# Generated by Django 4.2.1 on 2023-06-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afritechjobsapi', '0010_joblevel_joblocation_jobskills_jobtype_postajob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postajob',
            name='job_location',
        ),
        migrations.DeleteModel(
            name='JobLocation',
        ),
    ]
