# Generated by Django 4.2.1 on 2023-06-09 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('afritechjobsapi', '0015_remove_postajob_created_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobLocations',
            new_name='JobLocation',
        ),
    ]
