# Generated by Django 4.2.1 on 2023-06-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afritechjobsapi', '0016_rename_joblocations_joblocation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobLocation',
            new_name='JobLocations',
        ),
    ]
