# Generated by Django 4.2.1 on 2023-06-09 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('afritechjobsapi', '0018_joblocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobLocation',
        ),
    ]
