# Generated by Django 4.2.1 on 2023-06-09 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('afritechjobsapi', '0019_delete_joblocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='postajob',
            name='job_location',
            field=models.ForeignKey(
                default='', on_delete=django.db.models.deletion.CASCADE, to='afritechjobsapi.joblocation'
            ),
        ),
        migrations.DeleteModel(
            name='JobLocations',
        ),
    ]
