# Generated by Django 4.2.1 on 2023-06-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afritechjobsapi', '0024_postajob_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postajob',
            name='created_by',
        ),
    ]
