# Generated by Django 4.2.1 on 2023-06-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('afritechjobsapi', '0027_postajob_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postajob',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afritechjobsapi.profile'),
        ),
    ]
