# Generated by Django 4.2.1 on 2023-06-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('afritechjobsapi', '0028_alter_postajob_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postajob',
            name='job_skills',
        ),
        migrations.AddField(
            model_name='postajob',
            name='job_skills',
            field=models.ManyToManyField(blank=True, null=True, to='afritechjobsapi.jobskills'),
        ),
    ]
