# Generated by Django 4.2.1 on 2023-06-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('afritechjobsapi', '0029_remove_postajob_job_skills_postajob_job_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobskills',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
