# Generated by Django 4.2.1 on 2023-06-16 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('afritechjobsapi', '0030_alter_jobskills_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postajob',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
