# Generated by Django 4.2.1 on 2023-06-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('afritechjobsapi', '0031_alter_postajob_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postajob',
            name='job_level',
        ),
        migrations.RemoveField(
            model_name='postajob',
            name='job_location',
        ),
        migrations.AddField(
            model_name='postajob',
            name='job_level',
            field=models.ManyToManyField(to='afritechjobsapi.joblevel'),
        ),
        migrations.AddField(
            model_name='postajob',
            name='job_location',
            field=models.ManyToManyField(to='afritechjobsapi.joblocations'),
        ),
    ]
