# Generated by Django 4.2.1 on 2023-07-10 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("afritechjobsapi", "0033_alter_blog_author_alter_event_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postajob",
            name="company_logo",
        ),
    ]
