# Generated by Django 4.2.1 on 2023-08-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("afritechjobsapi", "0034_remove_postajob_company_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalJobListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=200)),
                ("job_salary_range", models.IntegerField(blank=True)),
                ("job_description", models.TextField()),
                ("job_application_link", models.URLField()),
                ("company_name", models.CharField(max_length=200)),
                ("company_hq", models.CharField(max_length=200)),
                ("companys_website", models.URLField()),
                (
                    "company_contact_email",
                    models.EmailField(blank=True, max_length=200, null=True),
                ),
                ("company_description", models.TextField()),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(max_length=50)),
                (
                    "job_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="afritechjobsapi.category",
                    ),
                ),
                ("job_level", models.ManyToManyField(to="afritechjobsapi.joblevel")),
                (
                    "job_location",
                    models.ManyToManyField(to="afritechjobsapi.joblocations"),
                ),
                (
                    "job_skills",
                    models.ManyToManyField(
                        blank=True, null=True, to="afritechjobsapi.jobskills"
                    ),
                ),
                (
                    "job_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="afritechjobsapi.jobtype",
                    ),
                ),
            ],
        ),
    ]
