# Generated by Django 5.0.6 on 2024-07-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afritechjobsapi', '0036_alter_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postajob',
            name='created_by',
        ),
    ]
