# Generated by Django 5.0.6 on 2024-07-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afritechjobsapi', '0038_alter_jobtype_job_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblevel',
            name='job_level_choices',
            field=models.CharField(choices=[('Student', 'Student'), ('Intern', 'Intern'), ('Entrylevel', 'Entrylevel'), ('Midlevel', 'Midlevel'), ('Seniorlevel', 'Seniorlevel'), ('Cofounder', 'Cofounder'), ('Director', 'Director'), ('Manager', 'Manager'), ('Chief Executive Officer', 'Chief Executive Officer'), ('Chief Technology Officer', 'Chief Technology Officer'), ('Chief Marketing Officer', 'Chief Marketing Officer'), ('Cofounder', 'Cofounder'), ('Chief Financial Officer', 'Chief Financial Officer'), ('Chief Operating Officer', 'Chief Operating Officer')], default='Entrylevel', max_length=30),
        ),
    ]
