# Generated by Django 5.0.6 on 2024-08-14 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afritechjobsapi', '0040_alter_externaljoblisting_job_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postajob',
            name='job_level',
        ),
        migrations.AddField(
            model_name='postajob',
            name='job_level',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='afritechjobsapi.joblevel'),
            preserve_default=False,
        ),
    ]
